site_name: RADTorch - API Documentation
nav:
    - Home: index.md
    - Installation: install.md
    - Getting Started: start.md
    - Pipeline: pipeline.md
    - Core: core.md
    - Get Involved: involve.md
    - Copyrights: copyright.md
    - License: license.md

theme:
  features:
    - instant
  name: 'material'
  palette:
    primary: 'black'
    accent: 'deep orange'
  icon:
    logo: material/book

  favicon: 'img/radtorch_icon.ico'
repo_name: radtorch/radtorch
repo_url: https://github.com/radtorch/radtorch/
edit_uri: ''
markdown_extensions:
  - admonition
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra_css:
  - 'stylesheets/extra.css'

google_analytics:
  - UA-116382803-2
  - auto
